# Generated by Django 4.2.7 on 2024-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebnote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='ник', max_length=50)),
                ('text', models.TextField(help_text='отзыв')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
