CREATE TABLE IF NOT EXISTS students (
id INTEGER(4) NOT NULL AUTOINCREMENT PRIMARY KEY,
name NVARCHARE(50)
);

CREATE TABLE IF NOT EXISTS lessons (
id INTEGER(2) NOT NULL AUTOINCREMENT PRIMARY KEY,
name_l NVARCHARE(50),
date_time datetime2,
cabinet INTEGER(3)
);

CREATE TABLE IF NOT EXISTS groups (
id INTEGER(3) NOT NULL AUTOINCREMENT PRIMARY KEY,
name NVARCHARE(50),
id_s INTEGER(4),
id_l INTEGER(2),
FOREIGN KEY (id_s) REFERENCES students(id),
FOREIGN KEY (id_l) REFERENCES lessons(id)
);
